services:
  # https://github.com/emscripten-core/emsdk/blob/main/docker/README.md
  emscripten:
    build:
      context: .
    user: ${DOCKER_USER:-1000:1000}
    working_dir: /app
    volumes:
      - ./:/app
      - emscripten-cache:/emsdk/upstream/emscripten/cache

volumes:
  emscripten-cache:
